-- Check Tables structure
SELECT C.COLUMNNAME, C.COLUMNNUMBER, C.COLUMNDATATYPE, C.COLUMNDEFAULT
FROM SYS.SYSCOLUMNS C
JOIN SYS.SYSTABLES T ON C.REFERENCEID = T.TABLEID
WHERE T.TABLENAME = 'ARTICLES';

SELECT C.COLUMNNAME, C.COLUMNNUMBER, C.COLUMNDATATYPE, C.COLUMNDEFAULT
FROM SYS.SYSCOLUMNS C
JOIN SYS.SYSTABLES T ON C.REFERENCEID = T.TABLEID
WHERE T.TABLENAME = 'ARTICLE_TOPIC';

SELECT C.COLUMNNAME, C.COLUMNNUMBER, C.COLUMNDATATYPE, C.COLUMNDEFAULT
FROM SYS.SYSCOLUMNS C
JOIN SYS.SYSTABLES T ON C.REFERENCEID = T.TABLEID
WHERE T.TABLENAME = 'TOPICS';

SELECT C.COLUMNNAME, C.COLUMNNUMBER, C.COLUMNDATATYPE, C.COLUMNDEFAULT
FROM SYS.SYSCOLUMNS C
JOIN SYS.SYSTABLES T ON C.REFERENCEID = T.TABLEID
WHERE T.TABLENAME = 'USERS';

SELECT C.COLUMNNAME, C.COLUMNNUMBER, C.COLUMNDATATYPE, C.COLUMNDEFAULT
FROM SYS.SYSCOLUMNS C
JOIN SYS.SYSTABLES T ON C.REFERENCEID = T.TABLEID
WHERE T.TABLENAME = 'USER_ARTICLES';

-- Check Tables Content

SELECT * FROM ARTICLES;
SELECT * FROM ARTICLE_TOPIC;
SELECT * FROM TOPICS;
SELECT * FROM USERS;
SELECT * FROM USER_ARTICLES;