<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "homework1";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                // Tòpics
                "INSERT INTO " + schema + ".TOPICS VALUES (NEXT VALUE FOR TOPIC_GEN, 'Programming')",
                "INSERT INTO " + schema + ".TOPICS VALUES (NEXT VALUE FOR TOPIC_GEN, 'Technology')",
                "INSERT INTO " + schema + ".TOPICS VALUES (NEXT VALUE FOR TOPIC_GEN, 'Science')",

                // Usuaris (users)
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'sob', 'sob')",
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'admin', 'admin123')",
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'john_doe', 'password')",

                // Articles
                "INSERT INTO " + schema + ".ARTICLES VALUES (NEXT VALUE FOR ARTICLE_GEN, 'REST APIs are essential in modern web development.',  CURRENT_TIMESTAMP, 'REST APIs', 'Introduction to REST APIs', 0, 1)",
                "INSERT INTO " + schema + ".ARTICLES VALUES (NEXT VALUE FOR ARTICLE_GEN, 'JPA simplifies database interaction.', CURRENT_TIMESTAMP, 'Java Persistence', 'Learning Java Persistence', 0, 2)",
                "INSERT INTO " + schema + ".ARTICLES VALUES (NEXT VALUE FOR ARTICLE_GEN, 'Let us explore trends like AI and IoT.', CURRENT_TIMESTAMP, 'Technology Trends', 'Exploring Technology Trends', 0, 3)",

                // Relacions article-tòpic (ARTICLE_TOPICS)
                "INSERT INTO " + schema + ".ARTICLE_TOPIC VALUES (1, 1)", // REST APIs -> Programming
                "INSERT INTO " + schema + ".ARTICLE_TOPIC VALUES (2, 2)", // Learning JPA -> Technology
                "INSERT INTO " + schema + ".ARTICLE_TOPIC VALUES (3, 3)"  // Technology Trends -> Science
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
