<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "homework1";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                // Tòpics
                "INSERT INTO " + schema + ".TOPICS VALUES (NEXT VALUE FOR TOPIC_GEN, 'Bitcoin')",
                "INSERT INTO " + schema + ".TOPICS VALUES (NEXT VALUE FOR TOPIC_GEN, 'Blockchains')",
                "INSERT INTO " + schema + ".TOPICS VALUES (NEXT VALUE FOR TOPIC_GEN, 'JavaScript')",
                "INSERT INTO " + schema + ".TOPICS VALUES (NEXT VALUE FOR TOPIC_GEN, 'WebAssembly')",
                
                // Usuaris (users)
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'sob', 'sob')",
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'admin123', 'admin')",
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'password123', 'john_doe')",
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'securepass', 'jane_smith')",
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'mypassword', 'charlie_brown')",
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'passw0rd!', 'alice_wonder')",
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'qwerty123', 'bob_builder')",
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'letmein!', 'dora_explorer')",
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'password456', 'harry_potter')",
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'admin123', 'lara_croft')",
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'hunter2', 'peter_parker')",
                "INSERT INTO " + schema + ".USERS VALUES (NEXT VALUE FOR USER_GEN, 'trustno1', 'tony_stark')",


                // Articles
                "INSERT INTO " + schema + ".ARTICLES VALUES ("
                    + "NEXT VALUE FOR ARTICLE_GEN, "
                    + "1, "
                    + "'Bitcoin is rising up by 300% due to the government inflation.',  "
                    + "'https://picsum.photos/id/237/200/300', "
                    + "0, "
                    + "CURRENT_TIMESTAMP, "
                    + "'Bitcoin raising explained', "
                    + "'Bitcoin Rise', "
                    + "0)",
                "INSERT INTO " + schema + ".ARTICLES VALUES ("
                    + "NEXT VALUE FOR ARTICLE_GEN, "
                    + "1, "
                    + "'A blockchain is a distributed ledger with growing lists of records (blocks) that are securely linked together via cryptographic hashes.', "
                    + "'https://picsum.photos/200/300', "
                    + "0, "
                    + "CURRENT_TIMESTAMP, "
                    + "'What is a blockchain?', "
                    + "'Blockchaing Tech', "
                    + "50220)",
                "INSERT INTO " + schema + ".ARTICLES VALUES ("
                    + "NEXT VALUE FOR ARTICLE_GEN, "
                    + "2, "
                    + "'JavaScript (JS) is a lightweight interpreted (or just-in-time compiled) programming language with first-class functions.', "
                    + "'https://picsum.photos/200', "
                    + "1, "
                    + "CURRENT_TIMESTAMP, "
                    + "'What exactly is JS?', "
                    + "'JavaScript Programming Language', "
                    + "3300)",
                    

                // Relacions article-tòpic (ARTICLE_TOPICS)
                "INSERT INTO " + schema + ".ARTICLE_TOPIC VALUES (1, 1)",
                "INSERT INTO " + schema + ".ARTICLE_TOPIC VALUES (2, 2)",
                "INSERT INTO " + schema + ".ARTICLE_TOPIC VALUES (3, 3)",
                "INSERT INTO " + schema + ".ARTICLE_TOPIC VALUES (3, 4)"
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
